"""Add OTP attempt tracking to User model

Revision ID: ce091e7a6404
Revises: c951776ccf49
Create Date: 2025-09-09 21:30:12.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce091e7a6404'
down_revision = 'c951776ccf49' # Make sure this matches the previous migration file
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_sent_at', sa.DateTime(timezone=True), nullable=True))
    
    # CORRECTED LINE: Added server_default='0' to handle existing rows.
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'otp_sent_at')
    # ### end Alembic commands ###

